sys_includes = ["stdio.h", "stdint.h"]
no_includes = true
include_guard = "DEEP_FILTER_H"
tab_width = 4
style = "Type"
language = "C"
cpp_compat = true

[const]
allow_static_const = false
allow_constexpr = false
